from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Tuple


Color = Tuple[int, int, int]
RGBA = Tuple[int, int, int, int]


@dataclass(frozen=True)
class TypographyStyle:
    name: str
    title_color: Color
    body_color: Color
    stroke_color: Color
    shadow_color: Color
    band_fill: RGBA
    band_radius: int
    title_scale: float
    body_scale: float
    stroke_title: int
    stroke_body: int
    glow: bool = False
    uppercase: bool = True
    backing: str = "soft_panel"
    title_fonts: Tuple[str, ...] = ()
    body_fonts: Tuple[str, ...] = ()
    align: str = "center"
    layout_template: str = "balanced"
    tracking: int = 0
    shadow_alpha: int = 150


STYLES: Dict[str, TypographyStyle] = {
    "classic_travel": TypographyStyle(
        name="classic_travel",
        title_color=(255, 246, 214),
        body_color=(255, 246, 214),
        stroke_color=(26, 31, 30),
        shadow_color=(0, 0, 0),
        band_fill=(18, 24, 24, 62),
        band_radius=4,
        title_scale=0.82,
        body_scale=0.62,
        stroke_title=4,
        stroke_body=2,
        backing="underline",
        title_fonts=("Bebas Neue Bold", "Bebas Neue Regular", "League Spartan Bold", "DejaVu Sans Condensed Bold"),
        body_fonts=("Cabin SemiBold", "Roboto Condensed Bold", "DejaVu Sans Condensed Bold"),
        layout_template="bottom_title",
        tracking=1,
    ),
    "cinematic": TypographyStyle(
        name="cinematic",
        title_color=(248, 248, 248),
        body_color=(248, 248, 248),
        stroke_color=(0, 0, 0),
        shadow_color=(0, 0, 0),
        band_fill=(0, 0, 0, 0),
        band_radius=8,
        title_scale=0.86,
        body_scale=0.66,
        stroke_title=4,
        stroke_body=2,
        backing="none",
        title_fonts=("Bebas Neue Bold", "League Spartan Black", "Impact", "DejaVu Sans Condensed Bold"),
        body_fonts=("Roboto Condensed Bold", "Cabin SemiBold", "Liberation Sans Bold"),
        layout_template="center_stack",
        tracking=1,
    ),
    "premium_ad": TypographyStyle(
        name="premium_ad",
        title_color=(255, 231, 168),
        body_color=(255, 255, 255),
        stroke_color=(10, 7, 4),
        shadow_color=(0, 0, 0),
        band_fill=(18, 12, 7, 0),
        band_radius=10,
        title_scale=0.80,
        body_scale=0.60,
        stroke_title=3,
        stroke_body=2,
        backing="none",
        title_fonts=("EBGaramond12 Bold", "Roboto Slab Bold", "Georgia Bold", "DejaVu Serif Bold"),
        body_fonts=("Cabin Medium", "Lato Bold", "Liberation Sans Bold"),
        layout_template="editorial",
    ),
    "bauhaus": TypographyStyle(
        name="bauhaus",
        title_color=(245, 45, 45),
        body_color=(255, 243, 76),
        stroke_color=(0, 0, 0),
        shadow_color=(0, 0, 0),
        band_fill=(0, 0, 0, 36),
        band_radius=0,
        title_scale=0.78,
        body_scale=0.58,
        stroke_title=3,
        stroke_body=2,
        backing="side_rule",
        title_fonts=("Bebas Neue Regular", "League Spartan Bold", "DejaVu Sans Condensed Bold"),
        body_fonts=("Comfortaa Bold", "Cabin SemiBold", "DejaVu Sans Bold"),
        layout_template="top_left",
        tracking=1,
    ),
    "neon": TypographyStyle(
        name="neon",
        title_color=(96, 255, 245),
        body_color=(255, 245, 107),
        stroke_color=(7, 0, 20),
        shadow_color=(255, 0, 180),
        band_fill=(7, 0, 22, 42),
        band_radius=10,
        title_scale=0.84,
        body_scale=0.62,
        stroke_title=3,
        stroke_body=2,
        glow=True,
        backing="none",
        title_fonts=("Comfortaa Bold", "League Spartan Black", "Avenir Next Heavy", "DejaVu Sans Condensed Bold"),
        body_fonts=("Roboto Condensed Bold", "Cabin SemiBold", "DejaVu Sans Bold"),
        layout_template="center_stack",
        tracking=1,
    ),
    "literary": TypographyStyle(
        name="literary",
        title_color=(245, 242, 232),
        body_color=(235, 232, 224),
        stroke_color=(40, 40, 40),
        shadow_color=(0, 0, 0),
        band_fill=(0, 0, 0, 32),
        band_radius=3,
        title_scale=0.74,
        body_scale=0.54,
        stroke_title=2,
        stroke_body=1,
        backing="none",
        uppercase=False,
        title_fonts=("EBGaramond12 Bold", "Roboto Slab Bold", "Georgia Bold", "DejaVu Serif Bold"),
        body_fonts=("EBGaramond12 Regular", "Georgia", "DejaVu Serif"),
        layout_template="editorial",
    ),
    "tech": TypographyStyle(
        name="tech",
        title_color=(165, 238, 255),
        body_color=(240, 252, 255),
        stroke_color=(0, 17, 30),
        shadow_color=(0, 0, 0),
        band_fill=(0, 22, 38, 48),
        band_radius=2,
        title_scale=0.80,
        body_scale=0.60,
        stroke_title=3,
        stroke_body=2,
        backing="side_rule",
        title_fonts=("Roboto Condensed Bold", "Comfortaa Bold", "DejaVu Sans Condensed Bold"),
        body_fonts=("Roboto Condensed Medium", "Cabin SemiBold", "DejaVu Sans Bold"),
        layout_template="left_column",
        tracking=1,
    ),
    "sport": TypographyStyle(
        name="sport",
        title_color=(255, 255, 255),
        body_color=(255, 205, 74),
        stroke_color=(0, 0, 0),
        shadow_color=(0, 0, 0),
        band_fill=(0, 0, 0, 55),
        band_radius=5,
        title_scale=0.88,
        body_scale=0.64,
        stroke_title=5,
        stroke_body=2,
        backing="underline",
        title_fonts=("Bebas Neue Bold", "League Spartan Black", "Impact", "DejaVu Sans Condensed Bold"),
        body_fonts=("Roboto Condensed Bold", "Arial Bold", "Liberation Sans Bold"),
        layout_template="dynamic_diagonal",
        tracking=1,
    ),
    "editorial_serif": TypographyStyle(
        name="editorial_serif",
        title_color=(248, 241, 226),
        body_color=(238, 230, 214),
        stroke_color=(34, 28, 24),
        shadow_color=(0, 0, 0),
        band_fill=(255, 248, 230, 0),
        band_radius=0,
        title_scale=0.76,
        body_scale=0.54,
        stroke_title=2,
        stroke_body=1,
        uppercase=False,
        backing="none",
        title_fonts=("EBGaramond12 Bold", "Roboto Slab Bold", "Georgia Bold", "DejaVu Serif Bold"),
        body_fonts=("EBGaramond12 Regular", "Georgia", "DejaVu Serif"),
        align="left",
        layout_template="editorial",
    ),
    "modern_minimal": TypographyStyle(
        name="modern_minimal",
        title_color=(250, 250, 246),
        body_color=(236, 236, 228),
        stroke_color=(18, 18, 18),
        shadow_color=(0, 0, 0),
        band_fill=(255, 255, 255, 0),
        band_radius=0,
        title_scale=0.72,
        body_scale=0.52,
        stroke_title=2,
        stroke_body=1,
        backing="none",
        title_fonts=("Cabin SemiBold", "Roboto Bold", "Helvetica Neue Bold", "DejaVu Sans Bold"),
        body_fonts=("Cabin Regular", "Roboto Regular", "DejaVu Sans"),
        align="left",
        layout_template="top_left",
        tracking=1,
    ),
    "playful_social": TypographyStyle(
        name="playful_social",
        title_color=(255, 246, 92),
        body_color=(255, 255, 255),
        stroke_color=(22, 20, 38),
        shadow_color=(255, 72, 132),
        band_fill=(255, 255, 255, 0),
        band_radius=14,
        title_scale=0.86,
        body_scale=0.62,
        stroke_title=4,
        stroke_body=2,
        backing="none",
        title_fonts=("Cabin Sketch Bold", "League Spartan Black", "Arial Rounded MT Bold", "DejaVu Sans Condensed Bold"),
        body_fonts=("Cabin SemiBold", "Arial Bold", "DejaVu Sans Bold"),
        layout_template="dynamic_diagonal",
        tracking=1,
    ),
    "clean_corporate": TypographyStyle(
        name="clean_corporate",
        title_color=(226, 246, 255),
        body_color=(244, 250, 255),
        stroke_color=(0, 28, 48),
        shadow_color=(0, 0, 0),
        band_fill=(12, 42, 65, 34),
        band_radius=4,
        title_scale=0.76,
        body_scale=0.56,
        stroke_title=2,
        stroke_body=1,
        backing="side_rule",
        title_fonts=("Roboto Condensed Bold", "League Spartan Bold", "DejaVu Sans Condensed Bold"),
        body_fonts=("Roboto Condensed Regular", "Cabin Medium", "DejaVu Sans Bold"),
        align="left",
        layout_template="left_column",
    ),
    "organic_market": TypographyStyle(
        name="organic_market",
        title_color=(255, 248, 210),
        body_color=(242, 255, 225),
        stroke_color=(34, 55, 28),
        shadow_color=(0, 0, 0),
        band_fill=(36, 72, 38, 0),
        band_radius=12,
        title_scale=0.78,
        body_scale=0.58,
        stroke_title=3,
        stroke_body=1,
        backing="none",
        uppercase=False,
        title_fonts=("Lobster Two Bold", "Cooper Black", "EBGaramond12 Bold", "DejaVu Serif Bold"),
        body_fonts=("Cabin SemiBold", "Lato Bold", "DejaVu Sans Bold"),
        layout_template="bottom_title",
    ),
    "luxury_fashion": TypographyStyle(
        name="luxury_fashion",
        title_color=(250, 238, 216),
        body_color=(244, 238, 230),
        stroke_color=(32, 22, 18),
        shadow_color=(0, 0, 0),
        band_fill=(0, 0, 0, 0),
        band_radius=0,
        title_scale=0.70,
        body_scale=0.50,
        stroke_title=1,
        stroke_body=1,
        backing="none",
        uppercase=True,
        title_fonts=("EBGaramond12 AllSC", "EBGaramond12 Bold", "Roboto Slab Bold", "DejaVu Serif Bold"),
        body_fonts=("EBGaramond12 Regular", "Roboto Light", "DejaVu Serif"),
        align="center",
        layout_template="editorial",
        tracking=3,
        shadow_alpha=95,
    ),
    "retro_pop": TypographyStyle(
        name="retro_pop",
        title_color=(255, 240, 67),
        body_color=(255, 255, 255),
        stroke_color=(19, 26, 46),
        shadow_color=(255, 72, 91),
        band_fill=(0, 0, 0, 0),
        band_radius=0,
        title_scale=0.90,
        body_scale=0.62,
        stroke_title=5,
        stroke_body=2,
        backing="none",
        title_fonts=("Cabin Sketch Bold", "League Spartan Black", "Bebas Neue Bold", "DejaVu Sans Condensed Bold"),
        body_fonts=("Roboto Condensed Bold", "Cabin SemiBold", "DejaVu Sans Bold"),
        layout_template="dynamic_diagonal",
        tracking=1,
        shadow_alpha=180,
    ),
    "handmade_marker": TypographyStyle(
        name="handmade_marker",
        title_color=(255, 250, 214),
        body_color=(255, 231, 92),
        stroke_color=(14, 14, 18),
        shadow_color=(0, 0, 0),
        band_fill=(0, 0, 0, 0),
        band_radius=0,
        title_scale=0.82,
        body_scale=0.58,
        stroke_title=3,
        stroke_body=2,
        backing="none",
        uppercase=False,
        title_fonts=("Yusei Magic Regular", "Cabin Sketch Bold", "DejaVu Sans Condensed Bold"),
        body_fonts=("Cabin Sketch Regular", "Cabin SemiBold", "DejaVu Sans Bold"),
        layout_template="dynamic_diagonal",
        shadow_alpha=130,
    ),
    "script_invite": TypographyStyle(
        name="script_invite",
        title_color=(255, 244, 231),
        body_color=(255, 251, 242),
        stroke_color=(52, 34, 30),
        shadow_color=(0, 0, 0),
        band_fill=(0, 0, 0, 0),
        band_radius=0,
        title_scale=0.74,
        body_scale=0.48,
        stroke_title=1,
        stroke_body=1,
        backing="none",
        uppercase=False,
        title_fonts=("Lobster Regular", "Lobster Two Bold", "EB Garamond Bold", "DejaVu Serif Bold"),
        body_fonts=("EBGaramond12 Regular", "Roboto Slab Regular", "DejaVu Serif"),
        layout_template="editorial",
        shadow_alpha=100,
    ),
    "brutalist_type": TypographyStyle(
        name="brutalist_type",
        title_color=(245, 245, 235),
        body_color=(255, 74, 52),
        stroke_color=(0, 0, 0),
        shadow_color=(0, 0, 0),
        band_fill=(0, 0, 0, 36),
        band_radius=0,
        title_scale=0.92,
        body_scale=0.60,
        stroke_title=2,
        stroke_body=1,
        backing="side_rule",
        title_fonts=("Bebas Neue Bold", "League Spartan Black", "DejaVu Sans Condensed Bold"),
        body_fonts=("Roboto Condensed Bold", "Cabin SemiBold", "DejaVu Sans Bold"),
        align="left",
        layout_template="left_column",
        tracking=2,
        shadow_alpha=90,
    ),
    "space_age": TypographyStyle(
        name="space_age",
        title_color=(210, 249, 255),
        body_color=(255, 255, 255),
        stroke_color=(1, 24, 44),
        shadow_color=(45, 214, 255),
        band_fill=(0, 0, 0, 0),
        band_radius=0,
        title_scale=0.78,
        body_scale=0.54,
        stroke_title=2,
        stroke_body=1,
        glow=True,
        backing="none",
        title_fonts=("Comfortaa Bold", "Roboto Condensed Bold", "DejaVu Sans Condensed Bold"),
        body_fonts=("Roboto Condensed Medium", "Cabin SemiBold", "DejaVu Sans Bold"),
        layout_template="center_stack",
        tracking=2,
        shadow_alpha=120,
    ),
}


CATEGORY_TO_STYLE = {
    "travel": "classic_travel",
    "movie": "cinematic",
    "ad": "premium_ad",
    "museum": "bauhaus",
    "concert": "neon",
    "book": "literary",
    "event": "tech",
    "fitness": "sport",
    "beauty": "premium_ad",
    "food": "organic_market",
    "education": "clean_corporate",
}


def style_for_category(category: str) -> str:
    return CATEGORY_TO_STYLE.get(category, "cinematic")


def get_style(style_name: str | None, category: str) -> TypographyStyle:
    name = style_name or style_for_category(category)
    return STYLES.get(name, STYLES[style_for_category(category)])


STYLE_NAMES = list(STYLES.keys())
